\contentsline {lstlisting}{\numberline {1.1}Ejercio de prueba \cite {web:vimgolf}}{24}
\contentsline {lstlisting}{\numberline {1.2}Otro ejercicio de c\IeC {\'o}digo}{25}
\contentsline {lstlisting}{\numberline {3.1}Ejercio de prueba \cite {web:vimgolf}}{52}
\contentsline {lstlisting}{\numberline {3.2}Otro ejercicio de c\IeC {\'o}digo}{53}
\contentsline {lstlisting}{\numberline {5.1}Ejercio de prueba \cite {web:vimgolf}}{81}
\contentsline {lstlisting}{\numberline {5.2}Otro ejercicio de c\IeC {\'o}digo}{82}
\contentsline {lstlisting}{\numberline {6.1}Ejercio de prueba \cite {web:vimgolf}}{100}
\contentsline {lstlisting}{\numberline {6.2}Otro ejercicio de c\IeC {\'o}digo}{101}
\contentsline {lstlisting}{\numberline {A.1}Otro ejercicio de c\IeC {\'o}digo}{128}
